// Mocks generated by Mockito 5.4.2 from annotations
// in web3modal_flutter/test/mock_classes.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:convert' as _i29;
import 'dart:typed_data' as _i30;
import 'dart:ui' as _i19;

import 'package:event/event.dart' as _i3;
import 'package:flutter/foundation.dart' as _i2;
import 'package:flutter/material.dart' as _i14;
import 'package:http/http.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i26;
import 'package:url_launcher/url_launcher.dart' as _i21;
import 'package:w_common/disposable.dart' as _i5;
import 'package:walletconnect_flutter_v2/apis/core/relay_client/i_message_tracker.dart'
    as _i10;
import 'package:walletconnect_flutter_v2/apis/core/relay_client/json_rpc_2/src/peer.dart'
    as _i28;
import 'package:walletconnect_flutter_v2/apis/core/relay_client/relay_client.dart'
    as _i27;
import 'package:walletconnect_flutter_v2/apis/core/relay_client/websocket/i_websocket_handler.dart'
    as _i11;
import 'package:walletconnect_flutter_v2/apis/core/store/i_generic_store.dart'
    as _i7;
import 'package:walletconnect_flutter_v2/apis/core/store/i_store.dart' as _i9;
import 'package:walletconnect_flutter_v2/apis/sign_api/i_sessions.dart' as _i8;
import 'package:walletconnect_flutter_v2/walletconnect_flutter_v2.dart' as _i6;
import 'package:web3modal_flutter/models/grid_item.dart' as _i32;
import 'package:web3modal_flutter/models/w3m_chain_info.dart' as _i18;
import 'package:web3modal_flutter/models/w3m_wallet_info.dart' as _i16;
import 'package:web3modal_flutter/services/blockchain_api_service/blockchain_api_utils.dart'
    as _i33;
import 'package:web3modal_flutter/services/blockchain_api_service/blockchain_identity.dart'
    as _i13;
import 'package:web3modal_flutter/services/explorer_service/explorer_service.dart'
    as _i15;
import 'package:web3modal_flutter/services/ledger_service/ledger_service.dart'
    as _i34;
import 'package:web3modal_flutter/services/network_service/network_service.dart'
    as _i31;
import 'package:web3modal_flutter/services/storage_service/storage_service.dart'
    as _i35;
import 'package:web3modal_flutter/utils/platform/i_platform_utils.dart' as _i23;
import 'package:web3modal_flutter/utils/platform/platform_utils.dart' as _i22;
import 'package:web3modal_flutter/utils/toast/toast_message.dart' as _i25;
import 'package:web3modal_flutter/utils/toast/toast_utils.dart' as _i24;
import 'package:web3modal_flutter/utils/url/url_utils.dart' as _i20;
import 'package:web3modal_flutter/web3modal_flutter.dart' as _i17;
import 'package:web3modal_flutter/widgets/widget_stack/widget_stack.dart'
    as _i36;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEvent_1<T extends _i3.EventArgs> extends _i1.SmartFake
    implements _i3.Event<T> {
  _FakeEvent_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_2<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeManagedDisposer_3 extends _i1.SmartFake
    implements _i5.ManagedDisposer {
  _FakeManagedDisposer_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimer_4 extends _i1.SmartFake implements _i4.Timer {
  _FakeTimer_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamSubscription_5<T1> extends _i1.SmartFake
    implements _i4.StreamSubscription<T1> {
  _FakeStreamSubscription_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompleter_6<T1> extends _i1.SmartFake implements _i4.Completer<T1> {
  _FakeCompleter_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeICore_7 extends _i1.SmartFake implements _i6.ICore {
  _FakeICore_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePairingMetadata_8 extends _i1.SmartFake
    implements _i6.PairingMetadata {
  _FakePairingMetadata_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeISignEngine_9 extends _i1.SmartFake implements _i6.ISignEngine {
  _FakeISignEngine_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIAuthEngine_10 extends _i1.SmartFake implements _i6.IAuthEngine {
  _FakeIAuthEngine_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIGenericStore_11<T> extends _i1.SmartFake
    implements _i7.IGenericStore<T> {
  _FakeIGenericStore_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeISessions_12 extends _i1.SmartFake implements _i8.ISessions {
  _FakeISessions_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIPairingStore_13 extends _i1.SmartFake implements _i6.IPairingStore {
  _FakeIPairingStore_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnectResponse_14 extends _i1.SmartFake
    implements _i6.ConnectResponse {
  _FakeConnectResponse_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthRequestResponse_15 extends _i1.SmartFake
    implements _i6.AuthRequestResponse {
  _FakeAuthRequestResponse_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIStore_16<T> extends _i1.SmartFake implements _i9.IStore<T> {
  _FakeIStore_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSessionData_17 extends _i1.SmartFake implements _i6.SessionData {
  _FakeSessionData_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIMessageTracker_18 extends _i1.SmartFake
    implements _i10.IMessageTracker {
  _FakeIMessageTracker_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIWebSocketHandler_19 extends _i1.SmartFake
    implements _i11.IWebSocketHandler {
  _FakeIWebSocketHandler_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_20 extends _i1.SmartFake implements _i12.Response {
  _FakeResponse_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_21 extends _i1.SmartFake
    implements _i12.StreamedResponse {
  _FakeStreamedResponse_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockchainIdentity_22 extends _i1.SmartFake
    implements _i13.BlockchainIdentity {
  _FakeBlockchainIdentity_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueListenable_23<T> extends _i1.SmartFake
    implements _i2.ValueListenable<T> {
  _FakeValueListenable_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_24 extends _i1.SmartFake implements _i14.Widget {
  _FakeWidget_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [ExplorerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExplorerService extends _i1.Mock implements _i15.ExplorerService {
  MockExplorerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get projectId => (super.noSuchMethod(
        Invocation.getter(#projectId),
        returnValue: '',
      ) as String);
  @override
  _i2.ValueNotifier<int> get totalListings => (super.noSuchMethod(
        Invocation.getter(#totalListings),
        returnValue: _FakeValueNotifier_0<int>(
          this,
          Invocation.getter(#totalListings),
        ),
      ) as _i2.ValueNotifier<int>);
  @override
  set totalListings(_i2.ValueNotifier<int>? _totalListings) =>
      super.noSuchMethod(
        Invocation.setter(
          #totalListings,
          _totalListings,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.ValueNotifier<List<_i16.W3MWalletInfo>> get listings =>
      (super.noSuchMethod(
        Invocation.getter(#listings),
        returnValue: _FakeValueNotifier_0<List<_i16.W3MWalletInfo>>(
          this,
          Invocation.getter(#listings),
        ),
      ) as _i2.ValueNotifier<List<_i16.W3MWalletInfo>>);
  @override
  set listings(_i2.ValueNotifier<List<_i16.W3MWalletInfo>>? _listings) =>
      super.noSuchMethod(
        Invocation.setter(
          #listings,
          _listings,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set featuredWalletIds(Set<String>? _featuredWalletIds) => super.noSuchMethod(
        Invocation.setter(
          #featuredWalletIds,
          _featuredWalletIds,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set includedWalletIds(Set<String>? _includedWalletIds) => super.noSuchMethod(
        Invocation.setter(
          #includedWalletIds,
          _includedWalletIds,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set excludedWalletIds(Set<String>? _excludedWalletIds) => super.noSuchMethod(
        Invocation.setter(
          #excludedWalletIds,
          _excludedWalletIds,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.ValueNotifier<bool> get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: _FakeValueNotifier_0<bool>(
          this,
          Invocation.getter(#initialized),
        ),
      ) as _i2.ValueNotifier<bool>);
  @override
  set initialized(_i2.ValueNotifier<bool>? _initialized) => super.noSuchMethod(
        Invocation.setter(
          #initialized,
          _initialized,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get recentWalletId => (super.noSuchMethod(
        Invocation.getter(#recentWalletId),
        returnValue: '',
      ) as String);
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> paginate() => (super.noSuchMethod(
        Invocation.method(
          #paginate,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  String getWalletImageUrl(String? imageId) => (super.noSuchMethod(
        Invocation.method(
          #getWalletImageUrl,
          [imageId],
        ),
        returnValue: '',
      ) as String);
  @override
  String getAssetImageUrl(String? imageId) => (super.noSuchMethod(
        Invocation.method(
          #getAssetImageUrl,
          [imageId],
        ),
        returnValue: '',
      ) as String);
  @override
  String? getRedirect({required String? name}) =>
      (super.noSuchMethod(Invocation.method(
        #getRedirect,
        [],
        {#name: name},
      )) as String?);
  @override
  void updateRecentPosition(String? recentId) => super.noSuchMethod(
        Invocation.method(
          #updateRecentPosition,
          [recentId],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void search({String? query}) => super.noSuchMethod(
        Invocation.method(
          #search,
          [],
          {#query: query},
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [W3MService].
///
/// See the documentation for Mockito's code generation for more information.
class MockW3MService extends _i1.Mock implements _i17.W3MService {
  MockW3MService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set connectResponse(_i6.ConnectResponse? _connectResponse) =>
      super.noSuchMethod(
        Invocation.setter(
          #connectResponse,
          _connectResponse,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Event<_i3.EventArgs> get onPairingExpire => (super.noSuchMethod(
        Invocation.getter(#onPairingExpire),
        returnValue: _FakeEvent_1<_i3.EventArgs>(
          this,
          Invocation.getter(#onPairingExpire),
        ),
      ) as _i3.Event<_i3.EventArgs>);
  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);
  @override
  Map<String, _i6.RequiredNamespace> get requiredNamespaces =>
      (super.noSuchMethod(
        Invocation.getter(#requiredNamespaces),
        returnValue: <String, _i6.RequiredNamespace>{},
      ) as Map<String, _i6.RequiredNamespace>);
  @override
  Map<String, _i6.RequiredNamespace> get optionalNamespaces =>
      (super.noSuchMethod(
        Invocation.getter(#optionalNamespaces),
        returnValue: <String, _i6.RequiredNamespace>{},
      ) as Map<String, _i6.RequiredNamespace>);
  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
      ) as bool);
  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> selectChain(
    _i18.W3MChainInfo? chainInfo, {
    bool? switchChain = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectChain,
          [chainInfo],
          {#switchChain: switchChain},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> openModal(
    _i14.BuildContext? context, [
    _i14.Widget? startWidget,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #openModal,
          [
            context,
            startWidget,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> expirePreviousInactivePairings() => (super.noSuchMethod(
        Invocation.method(
          #expirePreviousInactivePairings,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> buildConnectionUri() => (super.noSuchMethod(
        Invocation.method(
          #buildConnectionUri,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> connectWallet([_i16.W3MWalletInfo? walletInfo]) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectWallet,
          [walletInfo],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> launchConnectedWallet() => (super.noSuchMethod(
        Invocation.method(
          #launchConnectedWallet,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  String getReferer() => (super.noSuchMethod(
        Invocation.method(
          #getReferer,
          [],
        ),
        returnValue: '',
      ) as String);
  @override
  _i4.Future<void> reconnectRelay() => (super.noSuchMethod(
        Invocation.method(
          #reconnectRelay,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> disconnect({bool? disconnectAllSessions = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
          {#disconnectAllSessions: disconnectAllSessions},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void closeModal() => super.noSuchMethod(
        Invocation.method(
          #closeModal,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> selectWallet({required _i16.W3MWalletInfo? walletInfo}) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectWallet,
          [],
          {#walletInfo: walletInfo},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void launchBlockExplorer() => super.noSuchMethod(
        Invocation.method(
          #launchBlockExplorer,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(_i19.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i19.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UrlUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockUrlUtils extends _i1.Mock implements _i20.UrlUtils {
  MockUrlUtils() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> Function(String) get androidAppCheck => (super.noSuchMethod(
        Invocation.getter(#androidAppCheck),
        returnValue: (String uri) => _i4.Future<bool>.value(false),
      ) as _i4.Future<bool> Function(String));
  @override
  _i4.Future<bool> Function(
    Uri, {
    _i21.LaunchMode? mode,
  }) get launchUrlFunc => (super.noSuchMethod(
        Invocation.getter(#launchUrlFunc),
        returnValue: (
          Uri url, {
          _i21.LaunchMode? mode,
        }) =>
            _i4.Future<bool>.value(false),
      ) as _i4.Future<bool> Function(
        Uri, {
        _i21.LaunchMode? mode,
      }));
  @override
  _i4.Future<bool> Function(Uri) get canLaunchUrlFunc => (super.noSuchMethod(
        Invocation.getter(#canLaunchUrlFunc),
        returnValue: (Uri url) => _i4.Future<bool>.value(false),
      ) as _i4.Future<bool> Function(Uri));
  @override
  _i4.Future<bool> isInstalled(String? uri) => (super.noSuchMethod(
        Invocation.method(
          #isInstalled,
          [uri],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<bool> launchUrl(
    Uri? url, {
    _i21.LaunchMode? mode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #launchUrl,
          [url],
          {#mode: mode},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<void> launchRedirect({
    Uri? nativeUri,
    Uri? universalUri,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #launchRedirect,
          [],
          {
            #nativeUri: nativeUri,
            #universalUri: universalUri,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> navigateDeepLink({
    String? nativeLink,
    String? universalLink,
    required String? wcURI,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateDeepLink,
          [],
          {
            #nativeLink: nativeLink,
            #universalLink: universalLink,
            #wcURI: wcURI,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [PlatformUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformUtils extends _i1.Mock implements _i22.PlatformUtils {
  MockPlatformUtils() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.PlatformExact getPlatformExact() => (super.noSuchMethod(
        Invocation.method(
          #getPlatformExact,
          [],
        ),
        returnValue: _i23.PlatformExact.iOS,
      ) as _i23.PlatformExact);
  @override
  _i23.PlatformType getPlatformType() => (super.noSuchMethod(
        Invocation.method(
          #getPlatformType,
          [],
        ),
        returnValue: _i23.PlatformType.mobile,
      ) as _i23.PlatformType);
  @override
  bool canDetectInstalledApps() => (super.noSuchMethod(
        Invocation.method(
          #canDetectInstalledApps,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool isBottomSheet() => (super.noSuchMethod(
        Invocation.method(
          #isBottomSheet,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool isLongBottomSheet(_i14.Orientation? orientation) => (super.noSuchMethod(
        Invocation.method(
          #isLongBottomSheet,
          [orientation],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool isMobileWidth(double? width) => (super.noSuchMethod(
        Invocation.method(
          #isMobileWidth,
          [width],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [ToastUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockToastUtils extends _i1.Mock implements _i24.ToastUtils {
  MockToastUtils() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i25.ToastMessage?> get toasts => (super.noSuchMethod(
        Invocation.getter(#toasts),
        returnValue: _i4.Stream<_i25.ToastMessage?>.empty(),
      ) as _i4.Stream<_i25.ToastMessage?>);
  @override
  _i4.Future<Null> get didDispose => (super.noSuchMethod(
        Invocation.getter(#didDispose),
        returnValue: _i4.Future<Null>.value(),
      ) as _i4.Future<Null>);
  @override
  String get disposableTypeName => (super.noSuchMethod(
        Invocation.getter(#disposableTypeName),
        returnValue: '',
      ) as String);
  @override
  int get disposalTreeSize => (super.noSuchMethod(
        Invocation.getter(#disposalTreeSize),
        returnValue: 0,
      ) as int);
  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);
  @override
  bool get isLeakFlagSet => (super.noSuchMethod(
        Invocation.getter(#isLeakFlagSet),
        returnValue: false,
      ) as bool);
  @override
  bool get isOrWillBeDisposed => (super.noSuchMethod(
        Invocation.getter(#isOrWillBeDisposed),
        returnValue: false,
      ) as bool);
  @override
  _i4.Future<void> show(_i25.ToastMessage? message) => (super.noSuchMethod(
        Invocation.method(
          #show,
          [message],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<T> awaitBeforeDispose<T>(_i4.Future<T>? future) =>
      (super.noSuchMethod(
        Invocation.method(
          #awaitBeforeDispose,
          [future],
        ),
        returnValue: _i26.ifNotNull(
              _i26.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #awaitBeforeDispose,
                  [future],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #awaitBeforeDispose,
                [future],
              ),
            ),
      ) as _i4.Future<T>);
  @override
  _i4.Future<Null> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<Null>.value(),
      ) as _i4.Future<Null>);
  @override
  void flagLeak([String? description]) => super.noSuchMethod(
        Invocation.method(
          #flagLeak,
          [description],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<T> getManagedDelayedFuture<T>(
    Duration? duration,
    T Function()? callback,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getManagedDelayedFuture,
          [
            duration,
            callback,
          ],
        ),
        returnValue: _i26.ifNotNull(
              _i26.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #getManagedDelayedFuture,
                  [
                    duration,
                    callback,
                  ],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #getManagedDelayedFuture,
                [
                  duration,
                  callback,
                ],
              ),
            ),
      ) as _i4.Future<T>);
  @override
  _i5.ManagedDisposer getManagedDisposer(_i5.Disposer? disposer) =>
      (super.noSuchMethod(
        Invocation.method(
          #getManagedDisposer,
          [disposer],
        ),
        returnValue: _FakeManagedDisposer_3(
          this,
          Invocation.method(
            #getManagedDisposer,
            [disposer],
          ),
        ),
      ) as _i5.ManagedDisposer);
  @override
  _i4.Timer getManagedTimer(
    Duration? duration,
    void Function()? callback,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getManagedTimer,
          [
            duration,
            callback,
          ],
        ),
        returnValue: _FakeTimer_4(
          this,
          Invocation.method(
            #getManagedTimer,
            [
              duration,
              callback,
            ],
          ),
        ),
      ) as _i4.Timer);
  @override
  _i4.Timer getManagedPeriodicTimer(
    Duration? duration,
    void Function(_i4.Timer)? callback,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getManagedPeriodicTimer,
          [
            duration,
            callback,
          ],
        ),
        returnValue: _FakeTimer_4(
          this,
          Invocation.method(
            #getManagedPeriodicTimer,
            [
              duration,
              callback,
            ],
          ),
        ),
      ) as _i4.Timer);
  @override
  _i4.StreamSubscription<T> listenToStream<T>(
    _i4.Stream<T>? stream,
    void Function(T)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenToStream,
          [
            stream,
            onData,
          ],
          {
            #onError: onError,
            #onDone: onDone,
            #cancelOnError: cancelOnError,
          },
        ),
        returnValue: _FakeStreamSubscription_5<T>(
          this,
          Invocation.method(
            #listenToStream,
            [
              stream,
              onData,
            ],
            {
              #onError: onError,
              #onDone: onDone,
              #cancelOnError: cancelOnError,
            },
          ),
        ),
      ) as _i4.StreamSubscription<T>);
  @override
  T manageAndReturnTypedDisposable<T extends _i5.Disposable>(T? disposable) =>
      (super.noSuchMethod(
        Invocation.method(
          #manageAndReturnTypedDisposable,
          [disposable],
        ),
        returnValue: _i26.dummyValue<T>(
          this,
          Invocation.method(
            #manageAndReturnTypedDisposable,
            [disposable],
          ),
        ),
      ) as T);
  @override
  _i4.Completer<T> manageCompleter<T>(_i4.Completer<T>? completer) =>
      (super.noSuchMethod(
        Invocation.method(
          #manageCompleter,
          [completer],
        ),
        returnValue: _FakeCompleter_6<T>(
          this,
          Invocation.method(
            #manageCompleter,
            [completer],
          ),
        ),
      ) as _i4.Completer<T>);
  @override
  void manageDisposable(_i5.Disposable? disposable) => super.noSuchMethod(
        Invocation.method(
          #manageDisposable,
          [disposable],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void manageStreamController(_i4.StreamController<dynamic>? controller) =>
      super.noSuchMethod(
        Invocation.method(
          #manageStreamController,
          [controller],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<Null> onDispose() => (super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [],
        ),
        returnValue: _i4.Future<Null>.value(),
      ) as _i4.Future<Null>);
  @override
  _i4.Future<Null> onWillDispose() => (super.noSuchMethod(
        Invocation.method(
          #onWillDispose,
          [],
        ),
        returnValue: _i4.Future<Null>.value(),
      ) as _i4.Future<Null>);
}

/// A class which mocks [Web3App].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeb3App extends _i1.Mock implements _i6.Web3App {
  MockWeb3App() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get protocol => (super.noSuchMethod(
        Invocation.getter(#protocol),
        returnValue: '',
      ) as String);
  @override
  int get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: 0,
      ) as int);
  @override
  _i6.ICore get core => (super.noSuchMethod(
        Invocation.getter(#core),
        returnValue: _FakeICore_7(
          this,
          Invocation.getter(#core),
        ),
      ) as _i6.ICore);
  @override
  _i6.PairingMetadata get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakePairingMetadata_8(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i6.PairingMetadata);
  @override
  _i6.ISignEngine get signEngine => (super.noSuchMethod(
        Invocation.getter(#signEngine),
        returnValue: _FakeISignEngine_9(
          this,
          Invocation.getter(#signEngine),
        ),
      ) as _i6.ISignEngine);
  @override
  set signEngine(_i6.ISignEngine? _signEngine) => super.noSuchMethod(
        Invocation.setter(
          #signEngine,
          _signEngine,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.IAuthEngine get authEngine => (super.noSuchMethod(
        Invocation.getter(#authEngine),
        returnValue: _FakeIAuthEngine_10(
          this,
          Invocation.getter(#authEngine),
        ),
      ) as _i6.IAuthEngine);
  @override
  set authEngine(_i6.IAuthEngine? _authEngine) => super.noSuchMethod(
        Invocation.setter(
          #authEngine,
          _authEngine,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Event<_i6.SessionConnect> get onSessionConnect => (super.noSuchMethod(
        Invocation.getter(#onSessionConnect),
        returnValue: _FakeEvent_1<_i6.SessionConnect>(
          this,
          Invocation.getter(#onSessionConnect),
        ),
      ) as _i3.Event<_i6.SessionConnect>);
  @override
  _i3.Event<_i6.SessionEvent> get onSessionEvent => (super.noSuchMethod(
        Invocation.getter(#onSessionEvent),
        returnValue: _FakeEvent_1<_i6.SessionEvent>(
          this,
          Invocation.getter(#onSessionEvent),
        ),
      ) as _i3.Event<_i6.SessionEvent>);
  @override
  _i3.Event<_i6.SessionExpire> get onSessionExpire => (super.noSuchMethod(
        Invocation.getter(#onSessionExpire),
        returnValue: _FakeEvent_1<_i6.SessionExpire>(
          this,
          Invocation.getter(#onSessionExpire),
        ),
      ) as _i3.Event<_i6.SessionExpire>);
  @override
  _i3.Event<_i6.SessionProposalEvent> get onProposalExpire =>
      (super.noSuchMethod(
        Invocation.getter(#onProposalExpire),
        returnValue: _FakeEvent_1<_i6.SessionProposalEvent>(
          this,
          Invocation.getter(#onProposalExpire),
        ),
      ) as _i3.Event<_i6.SessionProposalEvent>);
  @override
  _i3.Event<_i6.SessionExtend> get onSessionExtend => (super.noSuchMethod(
        Invocation.getter(#onSessionExtend),
        returnValue: _FakeEvent_1<_i6.SessionExtend>(
          this,
          Invocation.getter(#onSessionExtend),
        ),
      ) as _i3.Event<_i6.SessionExtend>);
  @override
  _i3.Event<_i6.SessionPing> get onSessionPing => (super.noSuchMethod(
        Invocation.getter(#onSessionPing),
        returnValue: _FakeEvent_1<_i6.SessionPing>(
          this,
          Invocation.getter(#onSessionPing),
        ),
      ) as _i3.Event<_i6.SessionPing>);
  @override
  _i3.Event<_i6.SessionUpdate> get onSessionUpdate => (super.noSuchMethod(
        Invocation.getter(#onSessionUpdate),
        returnValue: _FakeEvent_1<_i6.SessionUpdate>(
          this,
          Invocation.getter(#onSessionUpdate),
        ),
      ) as _i3.Event<_i6.SessionUpdate>);
  @override
  _i3.Event<_i6.SessionDelete> get onSessionDelete => (super.noSuchMethod(
        Invocation.getter(#onSessionDelete),
        returnValue: _FakeEvent_1<_i6.SessionDelete>(
          this,
          Invocation.getter(#onSessionDelete),
        ),
      ) as _i3.Event<_i6.SessionDelete>);
  @override
  _i7.IGenericStore<_i6.ProposalData> get proposals => (super.noSuchMethod(
        Invocation.getter(#proposals),
        returnValue: _FakeIGenericStore_11<_i6.ProposalData>(
          this,
          Invocation.getter(#proposals),
        ),
      ) as _i7.IGenericStore<_i6.ProposalData>);
  @override
  _i8.ISessions get sessions => (super.noSuchMethod(
        Invocation.getter(#sessions),
        returnValue: _FakeISessions_12(
          this,
          Invocation.getter(#sessions),
        ),
      ) as _i8.ISessions);
  @override
  _i7.IGenericStore<_i6.SessionRequest> get pendingRequests =>
      (super.noSuchMethod(
        Invocation.getter(#pendingRequests),
        returnValue: _FakeIGenericStore_11<_i6.SessionRequest>(
          this,
          Invocation.getter(#pendingRequests),
        ),
      ) as _i7.IGenericStore<_i6.SessionRequest>);
  @override
  _i6.IPairingStore get pairings => (super.noSuchMethod(
        Invocation.getter(#pairings),
        returnValue: _FakeIPairingStore_13(
          this,
          Invocation.getter(#pairings),
        ),
      ) as _i6.IPairingStore);
  @override
  _i3.Event<_i6.AuthResponse> get onAuthResponse => (super.noSuchMethod(
        Invocation.getter(#onAuthResponse),
        returnValue: _FakeEvent_1<_i6.AuthResponse>(
          this,
          Invocation.getter(#onAuthResponse),
        ),
      ) as _i3.Event<_i6.AuthResponse>);
  @override
  _i7.IGenericStore<_i6.AuthPublicKey> get authKeys => (super.noSuchMethod(
        Invocation.getter(#authKeys),
        returnValue: _FakeIGenericStore_11<_i6.AuthPublicKey>(
          this,
          Invocation.getter(#authKeys),
        ),
      ) as _i7.IGenericStore<_i6.AuthPublicKey>);
  @override
  _i7.IGenericStore<String> get pairingTopics => (super.noSuchMethod(
        Invocation.getter(#pairingTopics),
        returnValue: _FakeIGenericStore_11<String>(
          this,
          Invocation.getter(#pairingTopics),
        ),
      ) as _i7.IGenericStore<String>);
  @override
  _i7.IGenericStore<_i6.StoredCacao> get completeRequests =>
      (super.noSuchMethod(
        Invocation.getter(#completeRequests),
        returnValue: _FakeIGenericStore_11<_i6.StoredCacao>(
          this,
          Invocation.getter(#completeRequests),
        ),
      ) as _i7.IGenericStore<_i6.StoredCacao>);
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i6.ConnectResponse> connect({
    Map<String, _i6.RequiredNamespace>? requiredNamespaces,
    Map<String, _i6.RequiredNamespace>? optionalNamespaces,
    Map<String, String>? sessionProperties,
    String? pairingTopic,
    List<_i6.Relay>? relays,
    List<List<String>>? methods = const [
      [
        r'wc_sessionPropose',
        r'wc_sessionRequest',
      ],
      [r'wc_authRequest'],
    ],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
          {
            #requiredNamespaces: requiredNamespaces,
            #optionalNamespaces: optionalNamespaces,
            #sessionProperties: sessionProperties,
            #pairingTopic: pairingTopic,
            #relays: relays,
            #methods: methods,
          },
        ),
        returnValue:
            _i4.Future<_i6.ConnectResponse>.value(_FakeConnectResponse_14(
          this,
          Invocation.method(
            #connect,
            [],
            {
              #requiredNamespaces: requiredNamespaces,
              #optionalNamespaces: optionalNamespaces,
              #sessionProperties: sessionProperties,
              #pairingTopic: pairingTopic,
              #relays: relays,
              #methods: methods,
            },
          ),
        )),
      ) as _i4.Future<_i6.ConnectResponse>);
  @override
  _i4.Future<dynamic> request({
    required String? topic,
    required String? chainId,
    required _i6.SessionRequestParams? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [],
          {
            #topic: topic,
            #chainId: chainId,
            #request: request,
          },
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
  @override
  void registerEventHandler({
    required String? chainId,
    required String? event,
    void Function(
      String,
      dynamic,
    )? handler,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerEventHandler,
          [],
          {
            #chainId: chainId,
            #event: event,
            #handler: handler,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> ping({required String? topic}) => (super.noSuchMethod(
        Invocation.method(
          #ping,
          [],
          {#topic: topic},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> disconnectSession({
    required String? topic,
    required _i6.WalletConnectError? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #disconnectSession,
          [],
          {
            #topic: topic,
            #reason: reason,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  Map<String, _i6.SessionData> getActiveSessions() => (super.noSuchMethod(
        Invocation.method(
          #getActiveSessions,
          [],
        ),
        returnValue: <String, _i6.SessionData>{},
      ) as Map<String, _i6.SessionData>);
  @override
  Map<String, _i6.SessionData> getSessionsForPairing(
          {required String? pairingTopic}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionsForPairing,
          [],
          {#pairingTopic: pairingTopic},
        ),
        returnValue: <String, _i6.SessionData>{},
      ) as Map<String, _i6.SessionData>);
  @override
  Map<String, _i6.ProposalData> getPendingSessionProposals() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSessionProposals,
          [],
        ),
        returnValue: <String, _i6.ProposalData>{},
      ) as Map<String, _i6.ProposalData>);
  @override
  _i4.Future<_i6.AuthRequestResponse> requestAuth({
    required _i6.AuthRequestParams? params,
    String? pairingTopic,
    List<List<String>>? methods = const [
      [
        r'wc_sessionPropose',
        r'wc_sessionRequest',
      ],
      [r'wc_authRequest'],
    ],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestAuth,
          [],
          {
            #params: params,
            #pairingTopic: pairingTopic,
            #methods: methods,
          },
        ),
        returnValue: _i4.Future<_i6.AuthRequestResponse>.value(
            _FakeAuthRequestResponse_15(
          this,
          Invocation.method(
            #requestAuth,
            [],
            {
              #params: params,
              #pairingTopic: pairingTopic,
              #methods: methods,
            },
          ),
        )),
      ) as _i4.Future<_i6.AuthRequestResponse>);
  @override
  Map<int, _i6.StoredCacao> getCompletedRequestsForPairing(
          {required String? pairingTopic}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedRequestsForPairing,
          [],
          {#pairingTopic: pairingTopic},
        ),
        returnValue: <int, _i6.StoredCacao>{},
      ) as Map<int, _i6.StoredCacao>);
  @override
  String formatAuthMessage({
    required String? iss,
    required _i6.CacaoRequestPayload? cacaoPayload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #formatAuthMessage,
          [],
          {
            #iss: iss,
            #cacaoPayload: cacaoPayload,
          },
        ),
        returnValue: '',
      ) as String);
}

/// A class which mocks [Sessions].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessions extends _i1.Mock implements _i6.Sessions {
  MockSessions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: '',
      ) as String);
  @override
  String get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: '',
      ) as String);
  @override
  _i9.IStore<dynamic> get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeIStore_16<dynamic>(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i9.IStore<dynamic>);
  @override
  _i3.Event<_i6.StoreCreateEvent<_i6.SessionData>> get onCreate =>
      (super.noSuchMethod(
        Invocation.getter(#onCreate),
        returnValue: _FakeEvent_1<_i6.StoreCreateEvent<_i6.SessionData>>(
          this,
          Invocation.getter(#onCreate),
        ),
      ) as _i3.Event<_i6.StoreCreateEvent<_i6.SessionData>>);
  @override
  _i3.Event<_i6.StoreUpdateEvent<_i6.SessionData>> get onUpdate =>
      (super.noSuchMethod(
        Invocation.getter(#onUpdate),
        returnValue: _FakeEvent_1<_i6.StoreUpdateEvent<_i6.SessionData>>(
          this,
          Invocation.getter(#onUpdate),
        ),
      ) as _i3.Event<_i6.StoreUpdateEvent<_i6.SessionData>>);
  @override
  _i3.Event<_i6.StoreDeleteEvent<_i6.SessionData>> get onDelete =>
      (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeEvent_1<_i6.StoreDeleteEvent<_i6.SessionData>>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.Event<_i6.StoreDeleteEvent<_i6.SessionData>>);
  @override
  _i3.Event<_i6.StoreSyncEvent> get onSync => (super.noSuchMethod(
        Invocation.getter(#onSync),
        returnValue: _FakeEvent_1<_i6.StoreSyncEvent>(
          this,
          Invocation.getter(#onSync),
        ),
      ) as _i3.Event<_i6.StoreSyncEvent>);
  @override
  Map<String, _i6.SessionData> get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: <String, _i6.SessionData>{},
      ) as Map<String, _i6.SessionData>);
  @override
  set data(Map<String, _i6.SessionData>? _data) => super.noSuchMethod(
        Invocation.setter(
          #data,
          _data,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.SessionData Function(dynamic) get fromJson => (super.noSuchMethod(
        Invocation.getter(#fromJson),
        returnValue: (dynamic __p0) => _FakeSessionData_17(
          this,
          Invocation.getter(#fromJson),
        ),
      ) as _i6.SessionData Function(dynamic));
  @override
  String get storageKey => (super.noSuchMethod(
        Invocation.getter(#storageKey),
        returnValue: '',
      ) as String);
  @override
  _i4.Future<void> update(
    String? topic, {
    int? expiry,
    Map<String, _i6.Namespace>? namespaces,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [topic],
          {
            #expiry: expiry,
            #namespaces: namespaces,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  bool has(String? key) => (super.noSuchMethod(
        Invocation.method(
          #has,
          [key],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i6.SessionData? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as _i6.SessionData?);
  @override
  List<_i6.SessionData> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <_i6.SessionData>[],
      ) as List<_i6.SessionData>);
  @override
  _i4.Future<void> set(
    String? key,
    _i6.SessionData? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> persist() => (super.noSuchMethod(
        Invocation.method(
          #persist,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> restore() => (super.noSuchMethod(
        Invocation.method(
          #restore,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void checkInitialized() => super.noSuchMethod(
        Invocation.method(
          #checkInitialized,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RelayClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelayClient extends _i1.Mock implements _i27.RelayClient {
  MockRelayClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Event<_i3.EventArgs> get onRelayClientConnect => (super.noSuchMethod(
        Invocation.getter(#onRelayClientConnect),
        returnValue: _FakeEvent_1<_i3.EventArgs>(
          this,
          Invocation.getter(#onRelayClientConnect),
        ),
      ) as _i3.Event<_i3.EventArgs>);
  @override
  _i3.Event<_i3.EventArgs> get onRelayClientDisconnect => (super.noSuchMethod(
        Invocation.getter(#onRelayClientDisconnect),
        returnValue: _FakeEvent_1<_i3.EventArgs>(
          this,
          Invocation.getter(#onRelayClientDisconnect),
        ),
      ) as _i3.Event<_i3.EventArgs>);
  @override
  _i3.Event<_i6.ErrorEvent> get onRelayClientError => (super.noSuchMethod(
        Invocation.getter(#onRelayClientError),
        returnValue: _FakeEvent_1<_i6.ErrorEvent>(
          this,
          Invocation.getter(#onRelayClientError),
        ),
      ) as _i3.Event<_i6.ErrorEvent>);
  @override
  _i3.Event<_i6.MessageEvent> get onRelayClientMessage => (super.noSuchMethod(
        Invocation.getter(#onRelayClientMessage),
        returnValue: _FakeEvent_1<_i6.MessageEvent>(
          this,
          Invocation.getter(#onRelayClientMessage),
        ),
      ) as _i3.Event<_i6.MessageEvent>);
  @override
  _i3.Event<_i6.SubscriptionEvent> get onSubscriptionCreated =>
      (super.noSuchMethod(
        Invocation.getter(#onSubscriptionCreated),
        returnValue: _FakeEvent_1<_i6.SubscriptionEvent>(
          this,
          Invocation.getter(#onSubscriptionCreated),
        ),
      ) as _i3.Event<_i6.SubscriptionEvent>);
  @override
  _i3.Event<_i6.SubscriptionDeletionEvent> get onSubscriptionDeleted =>
      (super.noSuchMethod(
        Invocation.getter(#onSubscriptionDeleted),
        returnValue: _FakeEvent_1<_i6.SubscriptionDeletionEvent>(
          this,
          Invocation.getter(#onSubscriptionDeleted),
        ),
      ) as _i3.Event<_i6.SubscriptionDeletionEvent>);
  @override
  _i3.Event<_i3.EventArgs> get onSubscriptionResubscribed =>
      (super.noSuchMethod(
        Invocation.getter(#onSubscriptionResubscribed),
        returnValue: _FakeEvent_1<_i3.EventArgs>(
          this,
          Invocation.getter(#onSubscriptionResubscribed),
        ),
      ) as _i3.Event<_i3.EventArgs>);
  @override
  _i3.Event<_i3.EventArgs> get onSubscriptionSync => (super.noSuchMethod(
        Invocation.getter(#onSubscriptionSync),
        returnValue: _FakeEvent_1<_i3.EventArgs>(
          this,
          Invocation.getter(#onSubscriptionSync),
        ),
      ) as _i3.Event<_i3.EventArgs>);
  @override
  set jsonRPC(_i28.Peer? _jsonRPC) => super.noSuchMethod(
        Invocation.setter(
          #jsonRPC,
          _jsonRPC,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Map<String, _i4.Future<dynamic>> get pendingSubscriptions =>
      (super.noSuchMethod(
        Invocation.getter(#pendingSubscriptions),
        returnValue: <String, _i4.Future<dynamic>>{},
      ) as Map<String, _i4.Future<dynamic>>);
  @override
  set pendingSubscriptions(
          Map<String, _i4.Future<dynamic>>? _pendingSubscriptions) =>
      super.noSuchMethod(
        Invocation.setter(
          #pendingSubscriptions,
          _pendingSubscriptions,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.IMessageTracker get messageTracker => (super.noSuchMethod(
        Invocation.getter(#messageTracker),
        returnValue: _FakeIMessageTracker_18(
          this,
          Invocation.getter(#messageTracker),
        ),
      ) as _i10.IMessageTracker);
  @override
  set messageTracker(_i10.IMessageTracker? _messageTracker) =>
      super.noSuchMethod(
        Invocation.setter(
          #messageTracker,
          _messageTracker,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i7.IGenericStore<String> get topicMap => (super.noSuchMethod(
        Invocation.getter(#topicMap),
        returnValue: _FakeIGenericStore_11<String>(
          this,
          Invocation.getter(#topicMap),
        ),
      ) as _i7.IGenericStore<String>);
  @override
  set topicMap(_i7.IGenericStore<String>? _topicMap) => super.noSuchMethod(
        Invocation.setter(
          #topicMap,
          _topicMap,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i11.IWebSocketHandler get socketHandler => (super.noSuchMethod(
        Invocation.getter(#socketHandler),
        returnValue: _FakeIWebSocketHandler_19(
          this,
          Invocation.getter(#socketHandler),
        ),
      ) as _i11.IWebSocketHandler);
  @override
  _i6.ICore get core => (super.noSuchMethod(
        Invocation.getter(#core),
        returnValue: _FakeICore_7(
          this,
          Invocation.getter(#core),
        ),
      ) as _i6.ICore);
  @override
  set core(_i6.ICore? _core) => super.noSuchMethod(
        Invocation.setter(
          #core,
          _core,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> publish({
    required String? topic,
    required String? message,
    required int? ttl,
    required int? tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publish,
          [],
          {
            #topic: topic,
            #message: message,
            #ttl: ttl,
            #tag: tag,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<String> subscribe({required String? topic}) => (super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [],
          {#topic: topic},
        ),
        returnValue: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);
  @override
  _i4.Future<void> unsubscribe({required String? topic}) => (super.noSuchMethod(
        Invocation.method(
          #unsubscribe,
          [],
          {#topic: topic},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> connect({String? relayUrl}) => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
          {#relayUrl: relayUrl},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<bool> handlePublish(
    String? topic,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handlePublish,
          [
            topic,
            message,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i12.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i12.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i4.Future<_i12.Response>.value(_FakeResponse_20(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i4.Future<_i12.Response>);
  @override
  _i4.Future<_i12.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i4.Future<_i12.Response>.value(_FakeResponse_20(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i4.Future<_i12.Response>);
  @override
  _i4.Future<_i12.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i29.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i4.Future<_i12.Response>.value(_FakeResponse_20(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i4.Future<_i12.Response>);
  @override
  _i4.Future<_i12.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i29.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i4.Future<_i12.Response>.value(_FakeResponse_20(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i4.Future<_i12.Response>);
  @override
  _i4.Future<_i12.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i29.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i4.Future<_i12.Response>.value(_FakeResponse_20(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i4.Future<_i12.Response>);
  @override
  _i4.Future<_i12.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i29.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i4.Future<_i12.Response>.value(_FakeResponse_20(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i4.Future<_i12.Response>);
  @override
  _i4.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);
  @override
  _i4.Future<_i30.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i4.Future<_i30.Uint8List>.value(_i30.Uint8List(0)),
      ) as _i4.Future<_i30.Uint8List>);
  @override
  _i4.Future<_i12.StreamedResponse> send(_i12.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i4.Future<_i12.StreamedResponse>.value(_FakeStreamedResponse_21(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i4.Future<_i12.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkService extends _i1.Mock implements _i31.NetworkService {
  MockNetworkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueNotifier<bool> get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: _FakeValueNotifier_0<bool>(
          this,
          Invocation.getter(#initialized),
        ),
      ) as _i2.ValueNotifier<bool>);
  @override
  set initialized(_i2.ValueNotifier<bool>? _initialized) => super.noSuchMethod(
        Invocation.setter(
          #initialized,
          _initialized,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<_i32.GridItem<_i18.W3MChainInfo>> get itemListComplete =>
      (super.noSuchMethod(
        Invocation.getter(#itemListComplete),
        returnValue: <_i32.GridItem<_i18.W3MChainInfo>>[],
      ) as List<_i32.GridItem<_i18.W3MChainInfo>>);
  @override
  set itemListComplete(
          List<_i32.GridItem<_i18.W3MChainInfo>>? _itemListComplete) =>
      super.noSuchMethod(
        Invocation.setter(
          #itemListComplete,
          _itemListComplete,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.ValueNotifier<List<_i32.GridItem<_i18.W3MChainInfo>>> get itemList =>
      (super.noSuchMethod(
        Invocation.getter(#itemList),
        returnValue:
            _FakeValueNotifier_0<List<_i32.GridItem<_i18.W3MChainInfo>>>(
          this,
          Invocation.getter(#itemList),
        ),
      ) as _i2.ValueNotifier<List<_i32.GridItem<_i18.W3MChainInfo>>>);
  @override
  set itemList(
          _i2.ValueNotifier<List<_i32.GridItem<_i18.W3MChainInfo>>>?
              _itemList) =>
      super.noSuchMethod(
        Invocation.setter(
          #itemList,
          _itemList,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void filterList({String? query}) => super.noSuchMethod(
        Invocation.method(
          #filterList,
          [],
          {#query: query},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void updateSort() => super.noSuchMethod(
        Invocation.method(
          #updateSort,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BlockchainApiUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockchainApiUtils extends _i1.Mock
    implements _i33.BlockchainApiUtils {
  MockBlockchainApiUtils() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get blockchainApiUriRoot => (super.noSuchMethod(
        Invocation.getter(#blockchainApiUriRoot),
        returnValue: '',
      ) as String);
  @override
  String get projectId => (super.noSuchMethod(
        Invocation.getter(#projectId),
        returnValue: '',
      ) as String);
  @override
  _i4.Future<_i13.BlockchainIdentity> getIdentity(
    String? address,
    int? chainId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdentity,
          [
            address,
            chainId,
          ],
        ),
        returnValue: _i4.Future<_i13.BlockchainIdentity>.value(
            _FakeBlockchainIdentity_22(
          this,
          Invocation.method(
            #getIdentity,
            [
              address,
              chainId,
            ],
          ),
        )),
      ) as _i4.Future<_i13.BlockchainIdentity>);
}

/// A class which mocks [LedgerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLedgerService extends _i1.Mock implements _i34.LedgerService {
  MockLedgerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<double> getBalance(
    String? rpcUrl,
    String? address,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBalance,
          [
            rpcUrl,
            address,
          ],
        ),
        returnValue: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);
  @override
  _i4.Future<String> fetchEnsName(
    String? rpcUrl,
    String? address,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchEnsName,
          [
            rpcUrl,
            address,
          ],
        ),
        returnValue: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);
  @override
  _i4.Future<String> fetchEnsAvatar(
    String? rpcUrl,
    String? address,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchEnsAvatar,
          [
            rpcUrl,
            address,
          ],
        ),
        returnValue: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i35.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);
  @override
  _i4.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [WidgetStack].
///
/// See the documentation for Mockito's code generation for more information.
class MockWidgetStack extends _i1.Mock implements _i36.WidgetStack {
  MockWidgetStack() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueListenable<_i14.Widget> get current => (super.noSuchMethod(
        Invocation.getter(#current),
        returnValue: _FakeValueListenable_23<_i14.Widget>(
          this,
          Invocation.getter(#current),
        ),
      ) as _i2.ValueListenable<_i14.Widget>);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i14.Widget getCurrent() => (super.noSuchMethod(
        Invocation.method(
          #getCurrent,
          [],
        ),
        returnValue: _FakeWidget_24(
          this,
          Invocation.method(
            #getCurrent,
            [],
          ),
        ),
      ) as _i14.Widget);
  @override
  void add(_i14.Widget? widget) => super.noSuchMethod(
        Invocation.method(
          #add,
          [widget],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void pop() => super.noSuchMethod(
        Invocation.method(
          #pop,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool canPop() => (super.noSuchMethod(
        Invocation.method(
          #canPop,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  void popUntil(_i2.Key? key) => super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [key],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool containsKey(_i2.Key? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);
  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addDefault() => super.noSuchMethod(
        Invocation.method(
          #addDefault,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(_i19.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i19.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
